accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logoutView, name="logout"),
    path("loggedout/", views.logged_out, name="logged_out"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('newArticle/', views.newArticle, name='newArticle'),
    path('save/', views.saveArticle, name='saveArticle'),
    path('<int:article_id>/update/', views.updateArticle, name="updateArticle"),
    path('<int:article_id>/delete/', views.deleteArticle, name="deleteArticle"),
    path('<int:article_id>/writeComment/', views.writeComment, name="writeComment"),
    path('uploadImage/', views.uploadImage, name="uploadImage"),
    path('deleteComment/', views.deleteComment, name="deleteComment"),
    path('search/',views.searchArticle, name="search"),
    ]

stateoftheart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from blog.deletion import SET_WITH
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

domain_choices = (("Chemistry","Chemistry"),
                  ("Environment and Ecology","Environment and Ecology"),
                  ("Physics","Physics"),
                  ( "Biological Sciences","Biological Sciences"),
                  ("Humanities and Social Sciences","Humanities and Social Sciences"),
                  ("Systems Engineering","Systems Engineering"),
                  ("Mathematical Sciences","Mathematical Sciences"),
                  ("Astronomy and Astrophysics","Astronomy and Astrophysics"),
                  ("Earth Sciences","Earth Sciences"),
                  ("Information Sciences","Information Sciences"),
                  ("Nuclear and Particle Physics","Nuclear and Particle Physics"),
                  ("Other","Other"))


class Article(models.Model) :
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    abstract = models.TextField(blank=True)
    publishing_date = models.DateField(default=timezone.now)
    data = models.TextField()
    header_img = models.ImageField(upload_to='headers', blank=True, null=True)
    domain = models.CharField(max_length=250,default = "Other", choices = domain_choices)

    def __str__(self):
        return self.title

class Comment(models.Model) :
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    publishing_date = models.DateTimeField()
    text = models.TextField()
    parent = models.ForeignKey('self',on_delete=models.CASCADE,blank=True, related_name="children",null=True)

class Tag(models.Model) :
    name = models.CharField(max_length=250)
    articles = models.ManyToManyField(Article)

    def __str__(self):
        return self.name


# -----------------------Chapter before using Editor.js----------------------

# # getPreviousChapter is a method that connects two chapters that succeeds each other
# # in case of deletion of one Chapter 
# # function to call with on_delete with previous Field
# # the value given is the previous value of the chapter deleted
# def getPreviousChapter(chapter):
#     previous = Chapter.objects.get(id=chapter.previous.id).previous
#     return previous


# # a Chapter is part of an Article, parent Chapter is provided if exists
# # if doesn't exist it's a root Chapter.
# # previous

# class Chapter(models.Model) :
#     article = models.ForeignKey(Article, on_delete=models.CASCADE)
#     title = models.CharField(max_length=250,blank=True)
#     parent = models.ForeignKey('self', on_delete=models.CASCADE,blank=True, related_name="children",null=True)
#     previous = models.ForeignKey('self', blank=True, on_delete=SET_WITH(getPreviousChapter), related_name="next", null=True)
#     text = models.TextField(blank=True)

#     def __str__(self):
#         text = self.title
#         if (self.parent) :
#             text+=" | child of "+ self.parent.title
#         if (self.previous) :
#             text+=" | follows "+ self.previous.title
#         return text

blog/forms.py
from django import forms
from .models import *

class ArticleForm(forms.ModelForm):
    
    class Meta :
        model = Article
        fields = ['title','domain', 'abstract', 'publishing_date', 'header_img', 'data']
        widgets = {
            'title': forms.Textarea(attrs={'placeholder': 'Title', 'rows': 2}),
            'domain': forms.Select(attrs={'placeholder': 'Select the area of science'}),
            'abstract': forms.Textarea(attrs={'placeholder': 'Abstract'}),
        }

blog/views.py
from django.http import HttpResponse
# Create your views here.
from django.views import generic
from django.shortcuts import get_object_or_404, render, redirect
from blog.models import Article, Comment, Tag
from .forms import *


import json
from django.utils import timezone
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from PIL import Image
from io import BytesIO
import os
from django.conf import settings


def home(request) :
    article_list = Article.objects.order_by('-publishing_date')
    if request.user.is_authenticated:
        return render(request, 'blog/home.html', context = {"article_list": article_list, "user": request.user})
    else :
        return render(request, 'blog/home.html', context = {"article_list": article_list})

# class IndexView(generic.ListView):
    
    
#     template_name = "blog/index.html"
#     context_object_name = "article_list"

#     def get_queryset(self):
#         """Return the last five articles published"""
#         return Article.objects.order_by('-publishing_date')
    
#     def get_context_data(self, **kwargs) :
#         context = super(IndexView, self).get_context_data(**kwargs)
#         context['user'] = 
#         return super().get_context_data(**kwargs)

def detail(request, article_id):
    
    article = get_object_or_404(Article, pk=article_id)

   
    class Block :
        def __init__(self,type, data) :
            self.type = type
            if type == "header" :
                self.text = data["text"]
                self.level = data["level"]
            elif type =="paragraph" :
                self.text = data["text"]
            elif type == "image" :
                self.url = data["file"]["url"]
                self.alt = data["caption"]
            elif type == "equation" :
                self.equation = data["equation"]
                self.caption = data["caption"]

    
    rawData = json.loads(article.data)
    data = []
    for rawBlock in rawData["blocks"] :
        data.append(Block(rawBlock["type"], rawBlock["data"]))

    comments = Comment.objects.filter(article=article).order_by("-publishing_date")

    return render(request, 'blog/detail.html', {"article":article, "data":data, "comments":comments, "user": request.user})

def newArticle(request) :
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    if request.method =='POST' :
        form = ArticleForm(request.POST, request.FILES)
    else :
        form = ArticleForm()
    return render(request, 'blog/newArticle.html', {'form' : form})

def saveArticle(request):
    
    if request.method =='POST' :
        if "articleId" in request.POST :
            article = get_object_or_404(Article, pk=request.POST["articleId"])
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid() :
                form.save()
                # article = get_object_or_404(Article, pk=request.POST["articleId"])
                if article.header_img == None or not article.header_img:
                    if article.domain == "Chemistry" :
                        article.header_img = "domains/chemistry.jpg"
                    elif article.domain == "Environment and Ecology" :
                        article.header_img = "domains/ecology.jpg"
                    elif article.domain == "Physics" :
                        article.header_img = "domains/physics.jpg"
                article.save()

                article.tag_set.clear()

                if request.POST["tags"] != " " :
                    tags = request.POST["tags"].split(" ");
                    del tags[0]
                    tags.pop()
                    if len(tags)!=0 :
                        for tag in tags :
                            normalTag = tag.lower()
                            if len(Tag.objects.filter(name=normalTag)) > 0  :
                                Tag.objects.get(name=normalTag).articles.add(article)
                            else :
                                newTag = Tag(name=normalTag)
                                newTag.save()
                                newTag.articles.add(article)

                
                return render(request, 'blog/articleSaved.html', context={
                "POST" : json.dumps(request.POST), "article": article,
                })

 
            else :
                return render(request, 'blog/articleSaved.html', context={"error":form.errors})

        else :
            form = ArticleForm(request.POST, request.FILES)
            if form.is_valid() :
                
                article = form.save(commit=False)
                article.author = request.user
                if article.header_img == None or not article.header_img:
                    if article.domain == "Chemistry" :
                        article.header_img = "domains/chemistry.jpg"
                    elif article.domain == "Environment and Ecology" :
                        article.header_img = "domains/ecology.jpg"
                    elif article.domain == "Physics" :
                        article.header_img = "domains/physics.jpg"
                article.save()

                if request.POST["tags"] != " " :
                    tags = request.POST["tags"].split(" ");
                    del tags[0]
                    tags.pop()
                    if len(tags)!=0 :
                        for tag in tags :
                            normalTag = tag.lower()
                            if len(Tag.objects.filter(name=normalTag)) > 0  :
                                Tag.objects.get(name=normalTag).articles.add(article)
                            else :
                                newTag = Tag(name=normalTag)
                                newTag.save()
                                newTag.articles.add(article)

                return render(request, 'blog/articleSaved.html', context={
                    "POST" : json.dumps(request.POST), 
                    "article": article,
                    })  
            else :
                return render(request, 'blog/articleSaved.html', context={"error":form.errors})

    # if "articleId" in request.POST :
    #     article = get_object_or_404(Article, pk=request.POST["articleId"])
    #     article.title = request.POST["articleTitle"]
    #     article.abstract = request.POST["articleAbstract"]
    #     article.data = request.POST["articleData"]
    #     article.save()

    # else :
    #     newArticle = Article(
    #         title = request.POST["articleTitle"],
    #         abstract = request.POST["articleAbstract"],
    #         publishing_date = timezone.now(),
    #         data = request.POST["articleData"]
    #     )
    #     newArticle.save()

    
def updateArticle(request, article_id) :
    article = get_object_or_404(Article, pk=article_id)
    form = ArticleForm(instance=article)
    tagsToAdd = ""

    for tag in article.tag_set.all() :
        tagsToAdd += tag.name+" "

    return render(request, 'blog/updateArticle.html', {
        "article":article,
        "form":form,
        "tagsToAdd":tagsToAdd,
        })

def deleteArticle(request, article_id) :
    article = get_object_or_404(Article, pk=article_id)
    article.delete()
    return redirect("blog:home")

@csrf_exempt
def uploadImage(request):
    if request.method == 'POST':
        # Accéder au contenu du champ image
        imageData = request.FILES['image'].read()

        image = Image.open(BytesIO(imageData))

        image_name = request.FILES['image'].name

        relative_path = "articlesContent/" + image_name

        absolute_path = os.path.join(settings.MEDIA_ROOT, relative_path)

        image.save(absolute_path, 'JPEG')

        absolute_url = settings.MEDIA_URL + relative_path
       
        response = { "success" : 1,
        "file": {
            "url" : absolute_url,
            "relativeUrl" : relative_path
                  
        }
        }

        return HttpResponse(json.dumps(response), content_type="application/json",)
    else:
        response = {
            "success": 0,
            "message": "An error occurred while uploading the image"
        }
        return HttpResponse(json.dumps(response), content_type="application/json")
    
    
    
def writeComment(request, article_id) :
    
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    
    article = get_object_or_404(Article, pk=article_id)

    # Ajout du commentaire dans la base de donnée si un nouveau commentaire est posté
    
    if request.method == "POST" :
        if request.user.is_authenticated :
            newComment = Comment(
                author = request.user,
                article = article,
                publishing_date = timezone.now(),
                text = request.POST["comment_text"])
            if "comment_parent" in request.POST :
                newComment.parent = Comment.objects.get(pk=request.POST["comment_parent"])
            newComment.save()

    return redirect("blog:detail", article_id = article_id)

def deleteComment(request) :
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    
    if request.method == 'POST' :
        commentToDelete = Comment.objects.get(pk=request.POST["commentId"])
        commentToDelete.delete()
        articleId = int(request.POST["articleId"])
        return redirect("blog:detail", article_id = articleId)

def searchArticle(request) :
       
    if request.method == 'POST' :
        tags = request.POST["queryText"].lower().split(" ")
        tagsString = '+'.join(tags)

        if request.POST["querySettings"]=="byTag" :
            forcounter = 0
            for tag in tags :
                if forcounter==0 :

blog/templates/blog/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <title>{% block title %}State of the art{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    {% block stylesheets %} {% endblock %}
</head>
<body>
    
    <header>
        <div class="headerLogo">
            <a href="{% url 'blog:home' %}"><p>State of the Art</p></a>
        </div>
        <nav>
            {% if not user.is_authenticated %}
                <a href="{% url 'login' %}">Log in</a>
                <a href="{% url 'accounts:signup' %}">Sign up</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:profile' %}">Profile</a>
                <a href="{% url 'accounts:logout' %}">Log out</a>
                <a href="{% url 'blog:newArticle' %}">Write</a>
            {% endif %}
            {% block nav %} {% endblock %}
        </nav>
    </header>

    {% block content %}{% endblock content %}
    {% load static %}
    <script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

blog/templates/blog/detail.html
{% extends './base.html' %}




{% block title %}{{ article.title|truncatechars:20 }}{% endblock title %}

{% block nav %}
<a href="{% url 'blog:home' %}">Home</a>
<a href="{% url 'blog:updateArticle' article_id=article.id %}">Update</a>
<a href="{% url 'blog:deleteArticle' article_id=article.id %}">Delete</a>
{% endblock %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'blog/css/detail.css' %}">

<div class="titleBannerWrapper">
    <p class="titleBanner">
        {{ article.title }}
    </p>
</div>


<div class="wrapper">

    <section class="tableOfContents">
        <div class="reduceButtonWrapper">
            <div class="blank"></div>
            <button class="reduceButton reduce" onclick="actionTableOfContents()">
                <img src="{% static 'blog/images/icons/ArrowBar.svg' %}" alt="Button to reduce the table of contents">
            </button>
        </div>
        <div class="tableOfContentsWrapper">
            <div class="tableOfContents_header">
                <h2>Table of Contents :</h2>
            </div>
            <div class="tableOfContents__content">
                {% for block in data %}
                    {% if block.type == "header" %}
                        <a href="#{{block.text|cut:' '}}">
                            <h{{block.level}}>
                                {% autoescape off %}    
                                    {{block.text}}
                                {% endautoescape %}
                            </h{{block.level}}>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
            <a href="#comments">
                <h2>Comments</h2>
            </a>
        </div>
    </section>


    <section class="article">
        <div class="articleHeader">
            <p class="articleDomain {{article.domain}}">{{ article.domain }}</p>
            <div class="articleHeader__illustration">
                {% if article.header_img %}
                <img src="{{ article.header_img.url }}" alt="">
                {% endif %}
            </div>
            <h1 class="articleTitle"> {{ article.title }} </h1>
            <p class="articleAuthor">Written by {{article.author}}</p>
            <p class="articlePublishingDate">Published on {{article.publishing_date}}</p>
            <p class="articleAbstract"> {{ article.abstract }} </p>
        </div>
        
        
        
        <div class="articleContent">
            {% for block in data %}
                {% if block.type == "header" %}
                    <h{{block.level}} id="{{block.text|cut:' '}}" class="articleAnchor">
                        {% autoescape off %}    
                        {{block.text}}
                        {% endautoescape %}
                    </h{{block.level}}>
                {% endif %}
                {% if block.type == "paragraph" %}
                    <p>
                        {% autoescape off %}
                        {{block.text}}
                        {% endautoescape %}
                    </p>
                {% endif %}
                {% if block.type == "image" %}
                    <div class="imgWrapper">
                        <img src="{{block.url}}" alt="{% autoescape off %}{{block.alt}}{% endautoescape %}">
                        <p>
                            {% autoescape off %}
                            {{block.alt}}
                            {% endautoescape %}
                        </p>
                    </div>
                {% endif %}
                {% if block.type == "equation" %}
                    <div class="equationWrapper">
                        <p class="equation">\[{{block.equation}}\]</p>
                        <p class="caption">{{block.caption}}</p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        
    </section>

    <section class="comments" id="comments">
        
        <div class = "commentsHeader">
            <div class="grey-bar"></div>
            <p>{{comments|length}} Comments</p>
            <div class="grey-bar"></div>
        </div>
        
        {% if user.is_authenticated %}
            <form action="{% url 'blog:writeComment' article.id %}" method="post">
                {% csrf_token %}
                <textarea name="comment_text" class="commentInputText" cols="30" rows="5" placeholder = "Enter your comment here..." required></textarea>
                <input type="submit" value="Post Comment" class="commentSubmit">
            </form>
        
        {% endif %}

        {% if not user.is_authenticated %}
            <p class="logInAdvice">Please log in to comment</p>
        {% endif %}

        
        <input type="hidden" value="{% url 'blog:deleteComment' %}" id="urlDeleteComment">

        {% for comment in comments %}
            {% if not comment.parent %}
            <div class="comment parentComment">
                <div class="commentHeader">
                    <div class="commentHeader__data">
                        <p class="commentAuthor">{{comment.author}}</p>
                        <p class="commentPublishingDate">{{comment.publishing_date|date:"F j, Y"}}</p>
                    </div>
                    <div class="commentHeader__buttons">
                        {% if user.is_authenticated %}
                        <button onclick="reply('{{comment.id}}')" class="replyButton">Reply</button>
                        {% endif %}
                        {% if user.id == comment.author.id  or user.id == article.author.id %}
                        <button onclick="deleteComment('{{comment.id}}','{{article.id}}')" class="deleteButton">Delete</button>
                        <form action="{% url 'blog:deleteComment' %}" method="post" id="deleteForm{{comment.id}}">
                            {% csrf_token %}
                        </form>
                        {% endif %}
                    </div>
                </div>
                <p class="commentText">{{comment.text}}</p>
                <form id="reply{{comment.id}}" method="post" action="{% url 'blog:writeComment' article.id %}">{% csrf_token %}</form>
                
                {% if comment.children.all|length > 0 %}
                {% include "./detail_children.html" with children=comment.children.all article=article %}
                {% endif %}

            </div>
            {% endif %}
        {% endfor %}
    </section>

</div>




{% for chapter in article.chapter_set.all %}
    {% if not chapter.parent and not chapter.previous %}
    <h2>{{chapter.title}}</h2>
        {% if chapter.text %}
        <p>{{chapter.text}}</p>
        {% endif %}

        {% if chapter.children.all|length > 0 %}
        {% include "./detail_children.html" with children=chapter.children.all level=3 %}
        {% endif %}

        {% if chapter.next %}
        {% include "blog/detail_next.html" with chapters=chapter.next.all level=2 %}
        {% endif %}

    {% endif %}

    
{% endfor %}

<script src="{% static 'blog/js/detail.js' %}"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

{% endblock content %}

blog/templates/blog/detail_children.html
{% for comment in children %}
    <div class="comment">
        <div class="commentHeader">
            <div class="commentHeader__data">
                <p class="commentAuthor">{{comment.author}}</p>
                <p class="commentPublishingDate">{{comment.publishing_date|date:"F j, Y"}}</p>
            </div>
            <div class="commentHeader__buttons">
                {% if user.is_authenticated %}
                <button onclick="reply('{{comment.id}}')" class="replyButton">Reply</button>
                {% endif %}
                {% if user.id == comment.author.id  or user.id == article.author.id %}
                <button onclick="deleteComment('{{comment.id}}','{{article.id}}')" class="deleteButton">Delete</button>
                <form action="{% url 'blog:deleteComment' %}" method="post" id="deleteForm{{comment.id}}">
                    {% csrf_token %}
                </form>
                {% endif %}
            </div>
        </div>
        <p class="commentText">{{comment.text}}</p>
        <form id="reply{{comment.id}}" method="post" action="{% url 'blog:writeComment' article.id %}">{% csrf_token %}</form>
        
        {% if comment.children.all|length > 0 %}
        {% include "blog/detail_children.html" with children=comment.children.all article=article %}
        {% endif %}
    
    </div>







    {% comment %}
    <h{{level}}>{{child.title}}</h{{level}}>
    <p>{{child.text}}</p>
    {% if child.children %}
        {% include "blog/detail_children.html" with children=child.children.all level=level|add:"1" %}
    {% endif %}
    {% if child.next %}
    {% include "blog/detail_next.html" with chapters=child.next.all level=level %}
    {% endif %}
    {% endcomment %}
{% endfor %}

blog/templates/blog/detail_next.html
{% for chapter in chapters %}
    {% if forloop.counter == 1 %}
        <h{{level}}>{{chapter.title}}</h{{level}}>
        <p>{{chapter.text}}</p>
        {% if chapter.children %}
            {% include "blog/detail_children.html" with children=chapter.children.all level=level|add:"1" %}
        {% endif %}
        {% if chapter.next %}
            {% include "blog/detail_next.html" with chapters=chapter.next.all level=level %}
        {% endif %}
    {% endif %}
{% endfor %}

blog/templates/blog/home.html
{% extends './base.html' %}

{% block title %}State of the art | Blogs{% endblock title %}


{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">

<div class="returnTop" onclick="goToTop()">
    <p>Back to Top</p>
</div>

<section class="search">
    <form action="{% url 'blog:search' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="queryText" placeholder="Click here to search for an article..." id="queryText" required>
        <div class="queryGrey">
            <select name="querySettings" id="querySettings" placeholder="---Select an option---">
                <option value="byTag">search by Tag</option>
                <option value="byTitle">search in Title</option>
            </select>
            <button id="querySubmit"><img src="{% static 'blog/images/icons/search.svg' %}" alt="Search icon"></button>
        </div>

    </form>

</section>



<section class="recentPosts">
    <div class="recentPosts__header">
        <div class="horizontalBar"></div>
        <h2 class="recentPosts__header">Recent Posts</h2>
        <div class="horizontalBar"></div>
    </div>





    <div class="articleGrid">
    {% for article in article_list %}
        <div class="articlePreview">
            
            
            {% if not article.header_img == None and article.header_img %}
                <div class="headerImg">
                    <img src="{{ article.header_img.url }}" alt="">
                </div>
            {% endif %}
            <div class="articleContent">
                <div class="{{ article.domain }} articleDomain" >
                    <p>{{article.domain}}</p>
                </div>
                <h3>
                    <a href="{% url 'blog:detail' article.id %}">
                        {{ article.title }}
                    </a>
                </h3>
                <p class="articlePublishingDate"> Published on {{ article.publishing_date }}</p>
                <p class="articleAuthor"> Written by {{ article.author.username }}</p>
                <p class="articleAbstract"> {{article.abstract|truncatechars:400}} </p>
            </div>
        </div>
        <div class="separator"></div>
    {% endfor %}
    </div>


</section>

{% comment %}
    <!-- <div class="articleGridCol">
        {% for article in article_list %}
            {% if forloop.counter|add:"1"|divisibleby:"3" %}
                <div class="articlePreview">
                    {% if not article.header_img == None %}
                        <div class="headerImg">
                            <img src="{{ article.header_img.url }}" alt="">
                        </div>
                    {% endif %}
                    <div class="articleContent">
                        <p class="articlePublishingDate">{{ article.publishing_date }}</p>
                        <h3>
                            <a href="{% url 'blog:detail' article.id %}">
                                {{ article.title }}
                            </a>
                        </h3>
                        <p> Written by {{ article.author.username }}</p>
                        <p> {{article.abstract}} </p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div> -->

{% endcomment %}
   
<script src="{% static 'blog/js/home.js' %}"></script>

{% endblock content %}

blog/templates/blog/newArticle.html
{% extends './base.html' %}

{% block title %}New article | State of the Art{% endblock title %}

{% block nav %}
<a href="{% url 'blog:home' %}">Home</a>
{% endblock %}


{% block content %}
<!-- <script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.26.5/dist/editor.min.js"></script> -->
{% load static %}
<link rel="stylesheet" href="{% static 'blog/css/newArticle.css' %}">


<form method="POST" action="{% url 'blog:saveArticle' %}" id="saveForm" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="titleWrapper" >
        {{ form.title.errors }} 
        {{ form.title }}
    </div>
    <div class="abstractWrapper" >
        {{ form.abstract.errors }} 
        {{ form.abstract }}
    </div>
    <div class="domainWrapper">
        {{ form.domain.errors }}
        <label for="{{ form.domain.id_for_label }}">Article's area of science : </label>
        {{ form.domain }}

    </div>
    <div class="publishingDateWrapper" >
        {{ form.publishing_date.errors }} 
        <label for="{{ form.publishing_date.id_for_label }}">Article's publishing date : </label>
        {{ form.publishing_date }}
    </div>
    <div class="tagsWrapper">
        <label for="newTag">Add some tags to define your article : </label>
        <input type="text" name="newTag" id="newTag">
        <button type="button" onclick="addTag()" class="tagsButton">+</button>
        <div class="tags"></div>
        <input type="hidden" name="tags" id="tags" value=" ">
    </div>
    <div class="headerImgWrapper" >
        {{ form.header_img.errors }} 
        <label for="{{ form.header_img.id_for_label }}">(Optional) Select an image to illustrate your article : </label>
        {{ form.header_img }}
    </div>
    {{ form.data.as_hidden }}

</form>
<div id="editorjs"></div>


<script type="text/javascript" src="{% static 'blog/js/editor/editor.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/editor/header.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/editor/image.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/editor/equation.js' %}"></script>
<script type='text/javascript' src="{% static 'blog/js/newArticle.js' %}"></script>

<button onclick="saveArticle()">Save</button>


{% endblock content %}